version: '3.2'
services:
  bitcoind-testnet:
    container_name: bitcoind-testnet
    image: lnpbp/bitcoind:nightly
    restart: unless-stopped
    command:
      - "-testnet"
      - "-txindex"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=10.0.0.0/8"
      - "-rpcallowip=172.16.0.0/12"
      - "-rpcallowip=192.168.0.0/16"
      - "-rpcauth=bitcoin:c15fb70bbb0239f9cfdfc8b5d48d67a2$$0c9257124cf65b816e06fb8c657de4c5cc458d3385ca8242ba7ac17b29aeb064"
    ports:
      - 18333:18333
    expose:
      - 18332
    volumes:
      - bitcoin:/var/lib/bitcoin
    networks:
      - bitcoinrpc

  electrs-testnet:
    container_name: electrs-testnet
    image: lnpbp/electrs:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-testnet
    environment:
      ELECTRS_NETWORK: "testnet"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind-testnet:18332"
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs-testnet:60001"
      ELECTRS_MONITORING_ADDR: "electrs-testnet:14223"
      ELECTRS_COOKIE_FILE: "/var/lib/bitcoin/testnet3/.cookie"
    ports:
      - 60001:60001
    expose:
      - 4223
    volumes:
      - type: volume
        source: bitcoin
        target: /var/lib/bitcoin
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: electrs
        target: /var/lib/electrs
        read_only: false
        volume:
          nocopy: true
    networks:
      - bitcoinrpc

  lightningd-testnet:
    container_name: lightningd-testnet
    image: lnpbp/lightningd:nightly
    restart: unless-stopped
    depends_on:
      - bitcoind-testnet
    command:
      - "--testnet"
      - "--log-level=debug"
      - "--bitcoin-rpcuser=bitcoin"
      - "--bitcoin-rpcpassword=bitcoin"
      - "--bitcoin-rpcconnect=bitcoind-testnet"
    ports:
      - 19735:9735
    volumes:
      - lightning:/var/lib/lightning
    networks:
      - bitcoinrpc

  rgbd-testnet:
    container_name: rgbd-testnet
    image: lnpbp/rgbd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-testnet
      - electrs-testnet
    environment:
      FUNGIBLED_RPC_ENDPOINT: "lnp://{node_id}@0.0.0.0:13025"
    command:
      - "-vvvv"
      - "--network=testnet"
    ports:
      - 13025:13025
    volumes:
      - rgb:/var/lib/rgb
    networks:
      - bitcoinrpc

  lnpd-testnet:
    container_name: lnpd-testnet
    image: lnpbp/lnpd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-testnet
      - electrs-testnet
      - rgbd-testnet
    command:
      - "-vvvv"
      - "--network=testnet"
    ports:
      - 9736:9735
    volumes:
      - lnp:/var/lib/lnp
    networks:
      - bitcoinrpc

volumes:
  bitcoin:
      external: "${BITCOIN_VOLUME_EXTERNAL:-false}"
  electrs:
      external: "${ELECTRS_VOLUME_EXTERNAL:-false}"
  lightning:
      external: "${LIGHTNING_VOLUME_EXTERNAL:-false}"
  rgb:
    external: "${RGB_VOLUME_EXTERNAL:-false}"
  lnp:
    external: "${LNP_VOLUME_EXTERNAL:-false}"

networks:
  bitcoinrpc:
    driver: bridge
