version: '3.2'
services:
  bitcoind-testnet:
    container_name: bitcoind-testnet
    build: ../../Dockerfile/bitcoind
    restart: unless-stopped
    command:
      - "-rpcuser=bitcoin -rpcpassword=bitcoin"
    ports:
      - 18332:18332 # Remove this if you do not wish for the external nodes to connect to this node
      - 18333:18333
    expose:
      - 18332
    volumes:
      - bitcoin:/var/lib/bitcoind
    networks:
      - bitcoinrpc

  electrs-testnet:
    container_name: electrs-testnet
    build: ../../Dockerfile/electrs
    restart: unless-stopped
    depends_on:
      - bitcoind-testnet
    environment:
      ELECTRS_NETWORK: "testnet"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind-testnet:18332"
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs-testnet:60001"
      ELECTRS_MONITORING_ADDR: "electrs-testnet:14223"
    ports:
      - 60001:60001
      - 4223:4223
    volumes:
      - type: volume
        source: bitcoin
        target: /var/lib/bitcoind
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: electrs
        target: /var/lib/electrs
        read_only: false
        volume:
          nocopy: true
    networks:
      - bitcoinrpc

  lightningd-testnet:
    container_name: lightningd-testnet
    build: ../../Dockerfile/lightningd
    restart: unless-stopped
    depends_on:
      - bitcoind-testnet
    environment:
      BITCOIN_RPC_USER: "bitcoin"
      BITCOIN_RPC_PASSWORD: "bitcoin"
      BITCOIN_RPC_CONNECT: "bitcoind-testnet"
      BITCOIN_RPC_PORT: "18332"
      LIGHTNING_NETWORK_FLAG: "--testnet"
      LIGHTNING_LOG_LEVEL: "debug"
    ports:
      - 9735:9735
    expose:
      - 9735
    volumes:
      - lightning:/var/lib/lightning
    networks:
      - bitcoinrpc

volumes:
  bitcoin:
      external: "${BITCOIN_VOLUME_EXTERNAL:-false}"
  electrs:
      external: "${ELECTRS_VOLUME_EXTERNAL:-false}"
  lightning:
      external: "${LIGHTNING_VOLUME_EXTERNAL:-false}"

networks:
  bitcoinrpc:
    driver: bridge
