version: '3'
services:
  bitcoin-mainnet:
    container_name: bitcoind
    image: lnpbp/bitcoind:latest
    ports:
      - "8332"
      - "8333" # Remove this if you do not wish for the external nodes to connect to this node
    volumes:
      - "blockchain:/var/lib/bitcoind"
  bitcoin-signet:
    container_name: bitcoind-signet
    image: lnpbp/bitcoind-signet:latest
    ports:
      - "38332"
      - "38333" # Remove this if you do not wish for the external nodes to connect to this node
    volumes:
      - "blockchain:/var/lib/bitcoind"
volumes:
  blockchain:
