version: '3'
services:
  bitcoin-mainnet:
    container_name: bitcoind
    # image: lnpbp/bitcoind:latest
    build: bitcoind
    command:
      - "-txindex -rpcuser=bitcoin -rpcpassword=bitcoin"
    ports:
      - "8332:8332"
      - "8333:8333" # Remove this if you do not wish for the external nodes to connect to this node
    expose:
      - "8333"
    volumes:
      - "/private/var/lib/bitcoin:/var/lib/bitcoind"
    networks:
      - "mainnet"

  electrs-mainnet:
    container_name: electrs
    build: electrs
    command:
      - "--daemon-rpc-addr bitcoin-mainnet"
    ports:
      - "50001:50001"
      - "4224:4224"
    volumes:
      - "/private/var/lib/bitcoin:/var/lib/bitcoind"
      - "/private/var/lib/electrs:/var/lib/electrs"
    networks:
      - "mainnet"

  bitcoin-signet:
    container_name: bitcoind-signet
    image: lnpbp/bitcoind-signet:latest
    command:
      - "-txindex -rpcuser=bitcoin -rpcpassword=bitcoin"
    ports:
      - "38332:38332"
      - "38333:38332" # Remove this if you do not wish for the external nodes to connect to this node
    volumes:
      - "/private/var/lib/bitcoin:/var/lib/bitcoind"

  lightning-mainnet:
    container_name: lightningd
    image: lnpbp/lightningd:latest
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "lightningd --mainnet --lightning-dir=$LIGHTNING_DATA --bitcoin-rpcconnect=bitcoind --bitcoin-rpcuser=bitcoin --bitcoin-rpcpassword=bitcoin"
    ports:
      - "9735:9735"
      - "9835:9835"
    volumes:
      - "/private/var/lib/lightning:/var/lib/lightningd"
    networks:
      - "mainnet"

  lightning-signet:
    container_name: lightningd
    image: lnpbp/lightningd:latest
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "lightningd --signet --lightning-dir=$LIGHTNING_DATA --bitcoin-rpcconnect=bitcoind-signet --bitcoin-rpcuser=bitcoin --bitcoin-rpcpassword=bitcoin"
    ports:
      - "9735:9735"
      - "9835:9835"
    volumes:
      - "/private/var/lib/lightning:/var/lib/lightningd"

# volumes:
#   blockchain:
#   channels:
#   electrs:

networks:
  mainnet:
    driver: bridge