version: '3.2'
services:
  lightning:
    container_name: lightning
    image: lnpbp/lightningd:latest
    restart: unless-stopped
    command:
      - "--mainnet"
      - "--bitcoin-rpcuser=bitcoin"
      - "--bitcoin-rpcpassword=bitcoin"
      - "--bitcoin-rpcconnect=bitcoind-mainnet"
      - "--log-level=debug"
    # ports:
    # - 29735:9735
    networks:
      - bitcoinrpc     
    volumes:
      - /home/orlovsky/.lightning:/var/lib/lightning

  bitcoind-mainnet:
    container_name: bitcoind-mainnet
    image: lnpbp/bitcoind:latest
    restart: unless-stopped
    command:
      - "-txindex"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=10.0.0.0/8"
      - "-rpcallowip=172.16.0.0/12"
      - "-rpcallowip=192.168.0.0/16"
      - "-rpcauth=bitcoin:c15fb70bbb0239f9cfdfc8b5d48d67a2$$0c9257124cf65b816e06fb8c657de4c5cc458d3385ca8242ba7ac17b29aeb064"
    ports:
      - 8333:8333
    expose:
      - 8332
    volumes:
      - bitcoin:/var/lib/bitcoin
    networks:
      - bitcoinrpc

  elementsd-liquidv1:
    container_name: elementsd-liquidv1
    image: lnpbp/elementsd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-mainnet
    command:
      - "-chain=liquidv1"
      - "-txindex"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=10.0.0.0/8"
      - "-rpcallowip=172.16.0.0/12"
      - "-rpcallowip=192.168.0.0/16"
      - "-rpcuser=bitcoin"
      - "-rpcpassword=bitcoin"
      - "-mainchainrpcuser=bitcoin"
      - "-mainchainrpcpassword=bitcoin"
      - "-mainchainrpchost=bitcoind-mainnet"
      - "-mainchainrpcport=8332"
    ports:
      - 7042:7042
    expose:
      - 7041
    volumes:
      - elements:/var/lib/elements
    networks:
      - bitcoinrpc

  electrs-mainnet:
    container_name: electrs-mainnet
    image: lnpbp/electrs:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-mainnet
    environment:
      RUSTi_LOG: "ERROR"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind-mainnet:8332"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind-mainnet:8333"
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs-mainnet:50001"
      ELECTRS_MONITORING_ADDR: "electrs-mainnet:4224"
      ELECTRS_COOKIE_FILE: "/var/lib/bitcoin/.cookie"
    expose:
      - 4224
    ports:
      - 50001:50001
    volumes:
      - type: volume
        source: bitcoin
        target: /var/lib/bitcoin
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: electrs
        target: /var/lib/electrs
        read_only: false
        volume:
          nocopy: true
    networks:
      - bitcoinrpc

  lightningd-mainnet:
    container_name: lightningd-mainnet
    image: lnpbp/lightningd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-mainnet
    command:
      - "--mainnet"
      - "--log-level=debug"
      - "--bitcoin-rpcuser=bitcoin"
      - "--bitcoin-rpcpassword=bitcoin"
      - "--bitcoin-rpcconnect=bitcoind-mainnet"
    ports:
      - 9735:9735
    volumes:
      - lightning:/var/lib/lightning
    networks:
      - bitcoinrpc

volumes:
  bitcoin:
    external: "${BITCOIN_VOLUME_EXTERNAL:-false}"
  elements:
    external: "${ELEMENTS_VOLUME_EXTERNAL:-false}"
  electrs:
    external: "${ELECTRS_VOLUME_EXTERNAL:-false}"
  lightning:
    external: "${LIGHTNING_VOLUME_EXTERNAL:-false}"

networks:
  bitcoinrpc:
    driver: bridge
