version: '3.2'
services:
  bitcoind-signet:
    container_name: bitcoind-signet
    build: ../bitcoind-signet
    restart: unless-stopped
    command:
      - "-rpcuser=bitcoin -rpcpassword=bitcoin"
    ports:
      - 38332:38332 # Remove this if you do not wish for the external nodes to connect to this node
      - 38333:38333
    expose:
      - 38332
      - 38333
    volumes:
      - bitcoin:/var/lib/bitcoin
    networks:
      - bitcoinrpc

  electrs-signet:
    container_name: electrs-signet
    build: ../electrs-signet
    restart: unless-stopped
    depends_on:
      - bitcoind-signet
    environment:
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind-signet:38332"
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs-signet:60601"
      ELECTRS_MONITORING_ADDR: "electrs-signet:34224"
    ports:
      - 60601:60601
      - 34224:34224
    expose:
      - 60601
    volumes:
      - type: volume
        source: bitcoin
        target: /var/lib/bitcoin
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: electrs
        target: /var/lib/electrs
        read_only: false
        volume:
          nocopy: true
    networks:
      - bitcoinrpc

  lightningd-signet:
    container_name: lightningd-signet
    build: ../lightningd
    restart: unless-stopped
    depends_on:
      - bitcoind-signet
    environment:
      BITCOIN_RPC_USER: "bitcoin"
      BITCOIN_RPC_PASSWORD: "bitcoin"
      BITCOIN_RPC_CONNECT: "bitcoind-signet"
      BITCOIN_RPC_PORT: "38332"
      LIGHTNING_NETWORK_FLAG: "--signet"
      LIGHTNING_LOG_LEVEL: "debug"
    ports:
      - 9735:9735
    expose:
      - 9735
    volumes:
      - lightning:/var/lib/lightning
    networks:
      - bitcoinrpc

volumes:
  bitcoin:
      external: "${BITCOIN_VOLUME_EXTERNAL:-false}"
  electrs:
      external: "${ELECTRS_VOLUME_EXTERNAL:-false}"
  lightning:
      external: "${LIGHTNING_VOLUME_EXTERNAL:-false}"

networks:
  bitcoinrpc:
    driver: bridge
