version: '3.2'
services:
  bitcoind-mainnet:
    container_name: bitcoind-mainnet
    build: ../bitcoind
    restart: unless-stopped
    command:
      - "-rpcuser=bitcoin -rpcpassword=bitcoin"
    ports:
      - 8332:8332 # Remove this if you do not wish for the external nodes to connect to this node
      - 8333:8333
    expose:
      - 8332
    volumes:
      - bitcoin:/var/lib/bitcoind
    networks:
      - bitcoinrpc

  electrs-mainnet:
    container_name: electrs-mainnet
    build: ../electrs
    restart: unless-stopped
    depends_on:
      - bitcoind-mainnet
    environment:
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind-mainnet:8332"
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs-mainnet:50001"
      ELECTRS_MONITORING_ADDR: "electrs-mainnet:4224"
    ports:
      - 50001:50001
      - 4224:4224
    volumes:
      - type: volume
        source: bitcoin
        target: /var/lib/bitcoind
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: electrs
        target: /var/lib/electrs
        read_only: false
        volume:
          nocopy: true
    networks:
      - bitcoinrpc

volumes:
  bitcoin:
    driver: local
    driver_opts:
      type: none
      device: /private/var/lib/bitcoin
      o: bind
  electrs:
    driver: local
    driver_opts:
      type: none
      device: /private/var/lib/electrs
      o: bind

networks:
  bitcoinrpc:
    driver: bridge
