version: '3.2'
services:
  bitcoind-signet:
    container_name: bitcoind-signet
    image: lnpbp/bitcoind:latest
    restart: unless-stopped
    command:
      - "-signet"
      - "-txindex"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=10.0.0.0/8"
      - "-rpcallowip=172.16.0.0/12"
      - "-rpcallowip=192.168.0.0/16"
      - "-rpcauth=bitcoin:c15fb70bbb0239f9cfdfc8b5d48d67a2$$0c9257124cf65b816e06fb8c657de4c5cc458d3385ca8242ba7ac17b29aeb064"
    ports:
      - 38333:38333
    expose:
      - 38332
    volumes:
      - bitcoin:/var/lib/bitcoin
    networks:
      - bitcoinrpc

  electrs-signet:
    container_name: electrs-signet
    image: lnpbp/electrs:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-signet
    environment:
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind-signet:38332"
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs-signet:60601"
      ELECTRS_MONITORING_ADDR: "electrs-signet:34224"
      ELECTRS_COOKIE_FILE: "/var/lib/bitcoin/signet/.cookie"
    ports:
      - 60601:60601
    expose:
      - 34224
    volumes:
      - type: volume
        source: bitcoin
        target: /var/lib/bitcoin
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: electrs
        target: /var/lib/electrs
        read_only: false
        volume:
          nocopy: true
    networks:
      - bitcoinrpc

  lightningd-signet:
    container_name: lightningd-signet
    image: lnpbp/lightningd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-signet
    command:
      - "--signet"
      - "--log-level=debug"
      - "--bitcoin-rpcuser=bitcoin"
      - "--bitcoin-rpcpassword=bitcoin"
      - "--bitcoin-rpcconnect=bitcoind-signet"
    ports:
      - 39735:9735
    volumes:
      - lightning:/var/lib/lightning
    networks:
      - bitcoinrpc

  rgbd-signet:
    container_name: rgbd-signet
    image: lnpbp/rgbd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind-signet
      - electrs-signet
    environment:
      FUNGIBLED_RPC_ENDPOINT: "lnp://{node_id}@0.0.0.0:13015"
    command:
      - "-vvvv"
    ports:
      - 13015:13015
    volumes:
      - rgb:/var/lib/rgb
    networks:
      - bitcoinrpc

volumes:
  bitcoin:
    external: "${BITCOIN_VOLUME_EXTERNAL:-false}"
  electrs:
    external: "${ELECTRS_VOLUME_EXTERNAL:-false}"
  lightning:
    external: "${LIGHTNING_VOLUME_EXTERNAL:-false}"
  rgb:
    external: "${RGB_VOLUME_EXTERNAL:-false}"

networks:
  bitcoinrpc:
    driver: bridge
