version: '3.2'
services:
  bitcoin-cli:
    container_name: bitcoin-cli
    build: ../bitcoind
    entrypoint: "bitcoin-cli -rpcconnect=bitcoind-mainnet -rpcuser=bitcoin -rpcpassword=bitcoin"
    networks:
      - bitcoinrpc
    external_links:
      - bitcoind-mainnet
      - electrs-mainnet

  netshoot:
    image: nicolaka/netshoot
    entrypoint: "/bin/bash"
    networks:
      - bitcoinrpc

networks:
  bitcoinrpc:
    external:
      name: mainnet_bitcoinrpc
